Added documentation (and enforcement) for yargs
ioBroker/create-adapter pull request #573
Opened 2020-09-07 12:47 UTC by UncleSamSwiss

- all arguments are now documented and shown when typing `--help`
- all arguments have shortcuts
- arguments can be passed using environment variables (mainly for testing)

2020-09-08 06:06 UTC, AlCalzone commented
>     * arguments can be passed using environment variables (mainly for testing)

How does that work? Could you add an example to the README please?

2020-09-08 06:30 UTC, AlCalzone commented
>     * all arguments have shortcuts

And how would that look like? Are they used with `=` like the long versions or a space before the argument?

2020-09-08 06:30 UTC, AlCalzone requested changes
See comments above

2020-09-09 07:20 UTC, UncleSamSwiss commented
> > ```
> > * arguments can be passed using environment variables (mainly for testing)
> > ```
> 
> How does that work? Could you add an example to the README please?

I will add this to the documentation. Just for reference, the environment variable feature works as follows:
https://yargs.js.org/docs/#api-reference-envprefix

2020-09-09 07:23 UTC, UncleSamSwiss commented
> > ```
> > * all arguments have shortcuts
> > ```
> 
> And how would that look like? Are they used with `=` like the long versions or a space before the argument?

As far as I know, yargs always supports `--parameter=abc` and `--parameter abc` for parameters with a value.
This change adds the possibility to say `-p=abc` or `-p abc` (notice the single dash).

2020-09-09 07:34 UTC, UncleSamSwiss commented
Note: failing build because of a 502 error - not related to my changes.

2020-09-09 08:27 UTC, AlCalzone requested changes
Whoopsie 🤷🏻‍♂️

2020-09-09 08:27 UTC, AlCalzone commented on README.md
> +All CLI options can also be [provided as environment varialbes](https://yargs.js.org/docs/#api-reference-envprefix) by prepending `CREATE_ADAPTER_`. Example: `CREATE_ADAPTER_TARGET=/tmp/iobroker/crea
```diff
- varialbes
+ variables
```

2020-09-09 08:31 UTC, UncleSamSwiss commented on README.md
> +All CLI options can also be [provided as environment varialbes](https://yargs.js.org/docs/#api-reference-envprefix) by prepending `CREATE_ADAPTER_`. Example: `CREATE_ADAPTER_TARGET=/tmp/iobroker/crea
Fixed.

2020-09-09 08:39 UTC, AlCalzone approved these changes

2020-09-09 10:52 UTC, AlCalzone commented
merged in 777f2cfee9c5577555eb0ee8437de47dd3a9020f

2020-09-09 10:52 UTC, closed without merging