Formatting
ioBroker/create-adapter pull request #71
Opened 2019-01-21 10:37 UTC by ldittmar81

Sonst springen die Texte hin un her bei der Übersetzung, denn dort werden 4 spaces und beim words2translation nur 2 hinzugefügt

**PR Checklist:**  
- [ ] Provide a meaningful description to this PR or mention which issues this fixes.
- [ ] Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).
- [ ] Run the test suite with `npm test`
- [ ] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
- [ ] Ensure the project builds with `npm run build` and include those artifacts aswell
- [ ] Add your changes to `CHANGELOG.md` (referencing this PR or the issue you fixed)

**Description:**  
add description here

2019-01-21 13:10 UTC, AlCalzone requested changes
Kannst du bitte die Checklist abarbeiten? Tests hinzufügen sollte in den meisten Fällen nicht nötig sein. 
Und bevorzugt sollte auch hier die Einstellung tabs vs spaces berücksichtigt werden.

2019-01-22 09:48 UTC, ldittmar81 commented
Wie wird das mit tabs vs spaces gemacht? Hab mal angeschaut... 
In der https://github.com/ioBroker/create-adapter/blob/master/templates/package.json.ts#L141 hast du 2 spaces und in der https://github.com/ioBroker/create-adapter/blob/master/templates/io-package.json.ts#L107 sind es 4. Zum Schluss soll alles 4 oder Tabs sein?

2019-01-22 10:19 UTC, AlCalzone commented
Package.json hat immer zwei spaces weil npm das beim neu schreiben so macht. Daher ist auch noReformat im template gesetzt.
Alles andere sollte konsistent sein. Dh wenn du whitespace am Anfang einer Zeile einfügst sollte je nach gewählter Option entweder `\t` oder `    ` vor dem Inhalt eingefügt werden.

Die eigentlichen code dateien werden automatisch formatiert, das wirkt sich aber nicht auf die aus die durch das gulpfile erzeugt werden. Daher sollte hier auch auf die Formatierung geachtet werden.

2019-01-22 10:21 UTC, AlCalzone commented
Die Anmerkung betrifft natürlich auch die anderen Stellen, wo der einzug festgelegt wird.

2019-01-22 12:33 UTC, AlCalzone commented on templates/gulpfile.js.ts
> +				const key = '    "' + w.replace(/"/g, '\\\\"') + '": ';
Example:
```js
const key = `${answers.indentation === "Tab" ? "\t" : "    "}"${w.replace(/"/g, '\\\\"')}": `;

2019-01-30 16:14 UTC, ldittmar81 commented
Out of date - ignore it

2019-01-30 16:14 UTC, closed without merging