Add version date and alphabetical order for i18n
ioBroker/create-adapter pull request #73
Opened 2019-01-22 09:44 UTC by ldittmar81

**PR Checklist:**  
- [ ] Provide a meaningful description to this PR or mention which issues this fixes.
- [ ] Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).
- [ ] Run the test suite with `npm test`
- [ ] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
- [ ] Ensure the project builds with `npm run build` and include those artifacts aswell
- [ ] Add your changes to `CHANGELOG.md` (referencing this PR or the issue you fixed)

**Description:**  
add description here

2019-01-22 10:15 UTC, AlCalzone commented
We should stay consistent. There is a similar comment in main.js/main.ts. Ideally those should be identical to the one in the gulpfile. And we should avoid placing them everywhere, so maybe in a single location?

2019-01-22 11:35 UTC, ldittmar81 commented
Ich verstehe was du meinst, aber die einzelnen Dateien haben ja nicht unbedingt was miteinander zu tun. Es kann sein, dass sich im gulpfile was ändert, ein neuen Task hinzugefügt wird, neue Funktionen z.B. automatischen Umzug zum iobroker-community-adapters, was geplant ist, und diese Änderungen betreffen ja NUR die gulpfile... hmm... kann man vielleicht die haupt gulpfile auslagern und in die gulpfile importieren? Wie z.B. mit dem adapter-core geschehen?

2019-01-22 11:47 UTC, ldittmar81 commented
Die gulpfile.js wird trotzdem benötigt, weil die Usern ja eigene Tasks einrichten können.

2019-01-22 12:39 UTC, AlCalzone commented
Achso, dein Plan ist es, ein Master-Gulpfile separat mit eigener Version zu pflegen und dann jeweils hier einfließen zu lassen? Dann OK!

Bitte noch die restlichen Punkte der Checkliste abarbeiten (außer Punkt 2, der ist bei einer kleinen Anpassung unnötig).

2019-01-22 12:45 UTC, AlCalzone requested changes
Achso, dein Plan ist es, ein Master-Gulpfile separat mit eigener Version zu pflegen und dann jeweils hier einfließen zu lassen? Dann OK!

Finde auch die Idee gut, das Gulpfile an einer Stelle zu pflegen. (Vielleicht sogar adapter-core?)

Bitte noch die restlichen Punkte der Checkliste abarbeiten (außer Punkt 2, der ist bei einer kleinen Anpassung unnötig).

2019-01-30 16:14 UTC, ldittmar81 commented
Out of date - ignore it

2019-01-30 16:14 UTC, closed without merging