Switch build process from `parcel` to `@iobroker/adapter-dev` using `esbuild`
ioBroker/create-adapter pull request #838
Opened 2021-10-17 22:01 UTC by AlCalzone

**PR Checklist:**

-   [x] Provide a meaningful description to this PR or mention which issues this fixes.
-   [ ] ~~Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).~~
-   [x] Run the test suite with `npm test`
-   [x] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
-   [x] Ensure the project builds with `npm run build`
-   [ ] ~~If you added a required option, also add it to the template creation (`.github/create_templates.ts`)~~
-   [x] Add a detailed migration description to `docs/updates` explaining what the user needs to do when manually updating an existing project
-   [x] Add your changes to `CHANGELOG.md` (referencing the migration description and this PR or the issue you fixed)

**Description:**  
ESBuild is much, much faster than Parcel and understands things like `package.json` exports, which parcel v1 doesn't support.

Note that we should also switch to https://github.com/AlCalzone/iobroker-react, because currently this results in some "compiled" css files that are imported from `adapter-react` somehow. I prefer to do this in a separate PR though.

2021-10-19 18:36 UTC, UncleSamSwiss requested changes
Found some issues.
I didn't test the creator with the changes myself.

2021-10-19 18:36 UTC, UncleSamSwiss commented on templates/_build.js.ts
> +			outdir: "admin/build",
I think, we should start using different outdirs for "watch" and "prod" builds. We could use a `.temp` directory for both builds if we are not creating a productive build.

2021-10-19 18:36 UTC, UncleSamSwiss commented on templates/_build.js.ts
> +	})().catch(() => process.exit(1));
How about printing the error to the console?
Or switch to ES2022 with async in the root ;-)

2021-10-19 18:36 UTC, UncleSamSwiss commented on templates/_build.js.ts
> +	})().catch(() => process.exit(1));
See comment above (log error)

2021-10-19 18:36 UTC, UncleSamSwiss commented on templates/_build.js.ts
> +import type { TemplateFunction } from "../src/lib/createAdapter";
Thinking about it (after looking at most of the changes), I believe we should actually move this script to adapter-dev and execute it from the scripts. Otherwise we have yet again a file that people need to update when something changes (we just got rid of gulpfile.js).

2021-10-19 18:36 UTC, UncleSamSwiss commented on templates/admin/index_m.html.ts
> +	<script type="module" src="build/index.js"></script>
Are modules supported by all older browsers that people might still use to run admin? Older tablets for example?
https://caniuse.com/es6-module

2021-10-19 20:29 UTC, AlCalzone commented on templates/_build.js.ts
> +			outdir: "admin/build",
Is that compatible with `dev-server`?

2021-10-19 20:32 UTC, AlCalzone commented on templates/_build.js.ts
> +	})().catch(() => process.exit(1));
> printing the error to the console

I don't think I've ever seen an actual error from the `build` call. I just wanted to make sure that the build fails, but yeah - we can log it.

TLA is supported in Node 14 - we can do that once we drop support for Node 12

2021-10-19 20:34 UTC, AlCalzone commented on templates/_build.js.ts
> +import type { TemplateFunction } from "../src/lib/createAdapter";
Not sure about this one. It would make sense, but there needs to be at least some configurability like the entry points or compilation target.
Also I had to disable bundling/minifying recently to diagnose a weird bug.

2021-10-19 20:36 UTC, AlCalzone commented on templates/admin/index_m.html.ts
> +	<script type="module" src="build/index.js"></script>
I'm not there at the meeting tomorrow, but this would be a good point for a discussion there. We can easily change the output format to CJS if desired.

2021-10-20 18:37 UTC, UncleSamSwiss commented on templates/_build.js.ts
> +			outdir: "admin/build",
Yes, as dev-server doesn't care about the output directory but simply "forwards" the right TCP port.

2021-10-20 18:44 UTC, UncleSamSwiss commented on templates/_build.js.ts
> +import type { TemplateFunction } from "../src/lib/createAdapter";
If you look at the `translate-adapter` tool, it also has the possibility to configure [all directories](https://github.com/ioBroker/adapter-dev/blob/284fe9abe9c744466c68e42433f355df08f53c1c/src/translate-adapter.ts#L44-L68) and has [different commands](https://github.com/ioBroker/adapter-dev/blob/284fe9abe9c744466c68e42433f355df08f53c1c/src/translate-adapter.ts#L18-L41).

2021-10-20 19:37 UTC, UncleSamSwiss commented on templates/admin/index_m.html.ts
> +	<script type="module" src="build/index.js"></script>
According to the dev meeting, this is acceptable.

2021-10-21 13:36 UTC, AlCalzone commented on templates/_build.js.ts
> +			outdir: "admin/build",
What's necessary to tell it where to find the admin sources? At the moment, this build script only re-compiles but does not start its own server like Parcel.

2021-10-21 13:44 UTC, AlCalzone commented on templates/_build.js.ts
> +	})().catch(() => process.exit(1));
logs added

2021-10-21 13:44 UTC, AlCalzone commented
Converting to draft for now - I like having the build script in adapter-dev.

2021-11-22 16:53 UTC, UncleSamSwiss commented
@AlCalzone Who is going to write the build script in adapter-dev?

2022-02-15 15:29 UTC, UncleSamSwiss commented
@AlCalzone adapter-dev 1.0.0 is released, you can now use it in this PR

2022-02-16 06:27 UTC, UncleSamSwiss approved these changes
LGTM Great work!

2022-02-16 06:28 UTC, merged