Use `@iobroker/adapter-dev` for development-related tasks
ioBroker/create-adapter pull request #839
Opened 2021-10-18 20:11 UTC by UncleSamSwiss

**PR Checklist:**

-   [x] Provide a meaningful description to this PR or mention which issues this fixes.
-   [x] Add tests for your change. This includes negative tests (i.e. inputs that need to fail) as well as baseline tests (i.e. how should the directory structure look like?).
-   [x] Run the test suite with `npm test`
-   [x] If there are baseline changes, review them and make a separate commit for them with the comment "accept baselines" if they are desired changes
-   [x] Ensure the project builds with `npm run build`
-   [ ] If you added a required option, also add it to the template creation (`.github/create_templates.ts`)
-   [x] Add a detailed migration description to `docs/updates` explaining what the user needs to do when manually updating an existing project
-   [x] Add your changes to `CHANGELOG.md` (referencing the migration description and this PR or the issue you fixed)

**Description:**  
- Using `@iobroker/adapter-dev` instead of `gulp` for translations in generated adapters
- Using `@iobroker/adapter-dev` internally in create-adapter when doing translations
- Offer the possibility to create the `i18n/<lang>/translations.json` files directly from create-adapter

2021-10-19 06:33 UTC, AlCalzone requested changes
Just some minor things

2021-10-19 06:33 UTC, AlCalzone commented on docs/updates/20211018_adapter-dev.md
> +| `gulp translate`                 | `npm run translate translate` |
See https://github.com/ioBroker/adapter-dev/issues/58 :)

2021-10-19 06:33 UTC, AlCalzone commented on docs/updates/20211018_adapter-dev.md
> +    - `axios` (except if you are using it in other development tasks)
```suggestion
    - `axios` (except if you are using it in other development tasks or in production)
```
I know you wrote devDependencies above, but better be sure :)

2021-10-19 06:33 UTC, AlCalzone commented on src/lib/core/questions.ts
> +				choices: ["words.js", "JSON"],
I would reformulate:
"How would you like to manage translations?"
* JSON files (hint = recommended, required for Weblate)
* words.js (hint = legacy)

2021-10-19 06:33 UTC, AlCalzone commented on templates/admin/src/i18n/zh-cn.json.ts
> +export = getI18nJsonTemplate("zh-cn", true);
Expanding a single template into an array would be handy now :D

2021-10-19 18:39 UTC, UncleSamSwiss commented on docs/updates/20211018_adapter-dev.md
> +| `gulp translate`                 | `npm run translate translate` |
Agreed, will go into a future release of adapter-dev.

2021-10-19 18:43 UTC, UncleSamSwiss commented on templates/admin/src/i18n/zh-cn.json.ts
> +export = getI18nJsonTemplate("zh-cn", true);
Yet again, yes.

2021-10-19 18:51 UTC, UncleSamSwiss commented on src/lib/core/questions.ts
> +				choices: ["words.js", "JSON"],
But we still keep words.js as the default, right?

2021-10-19 20:40 UTC, AlCalzone commented on src/lib/core/questions.ts
> +				choices: ["words.js", "JSON"],
I have no preference there.

2021-10-19 20:43 UTC, AlCalzone commented on src/lib/core/questions.ts
> +				choices: ["words.js", "JSON"],
Actually, I'm a bit confused now. I thought `words.js` is the only way for non-react and JSON files the recommended way for React and mandatory for Weblate. Should we even offer this question then?

2021-10-20 18:33 UTC, UncleSamSwiss commented on src/lib/core/questions.ts
> +				choices: ["words.js", "JSON"],
For regular HTML UIs you need to have a `words.js`, but you can also (additionally) manage the translations in JSON files. This is required for Weblate.
For React UIs you can only use JSON - for this reason the question is not asked if the user chooses to use a React UI (see line 648).

2021-10-21 06:08 UTC, AlCalzone commented on src/lib/core/questions.ts
> +				choices: ["words.js", "JSON"],
Ok the question now sounds like these are exclusive options, which isn't optimal. How about:
"How would you like to manage translations?"
* _Only words.js_ (default)
* _words.js and JSON files_ (hint = required for Weblate)

2021-10-21 19:06 UTC, UncleSamSwiss commented on src/lib/core/questions.ts
> +				choices: ["words.js", "JSON"],
I know we are splitting hairs here, but I agree with you that the question must be clearer. For me "managing" is where you write your translations. The fact that words.js is still used with JSON files shouldn't be so prominent. How about keeping the texts as before and just add something about `words.js` to the hint of `JSON`?

2021-10-21 20:44 UTC, AlCalzone commented on src/lib/core/questions.ts
> +				choices: ["words.js", "JSON"],
That could work too.

2021-11-22 16:51 UTC, UncleSamSwiss commented
@AlCalzone Clarified question about words.js once again. I think now this PR is ready to merge.

2022-02-15 17:37 UTC, AlCalzone approved these changes

2022-02-15 17:42 UTC, merged